#!/bin/bash
# ==============================================================================
# Automatic1111 (stable-diffusion-webui) installation
# ==============================================================================
# What this script deliberately no longer does
# --------------------------------------------
# The previous version generated a webui-user.sh containing:
#
#   export HSA_OVERRIDE_GFX_VERSION=11.0.0
#   export GPU_FORCE_64BIT_PTR=1
#   export GPU_MAX_HEAP_SIZE="100%"       # OpenCL-era AMD variables
#   export GPU_MAX_ALLOC_PERCENT="100%"
#   export PYTORCH_CUDA_ALLOC_CONF=""
#   COMMANDLINE_ARGS="... --medvram --no-half-vae"
#
# Every one of those is a problem on this stack:
#   * HSA_OVERRIDE_GFX_VERSION=11.0.0 forces gfx1100. With ROCDXG installed this
#     makes the runtime reject the device, hiding the GPU from PyTorch entirely.
#     It also misidentifies RDNA4 cards.
#   * The GPU_* variables are legacy OpenCL settings with no effect on ROCm.
#   * PYTORCH_CUDA_ALLOC_CONF is the wrong variable name for ROCm.
#   * --medvram forces partial model loading on cards that do not need it.
#
# The launch environment is now provided by lib/launch.sh, which sets the correct
# values for the detected GPU. This script only prepares the checkout.
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
export TOOLKIT_ROOT
# shellcheck disable=SC1091
. "$TOOLKIT_ROOT/lib/common.sh"
# shellcheck disable=SC1091
. "$TOOLKIT_ROOT/lib/launch.sh"
# shellcheck disable=SC1091
. "$TOOLKIT_ROOT/lib/tools.sh"

VENV_NAME="genai_env"
WEBUI_DIR="$HOME/stable-diffusion-webui"

standard_header "Automatic1111 — installation"

ai_load_env >/dev/null 2>&1 || true

ensure_venv "$VENV_NAME" || { err "Install the base environment first."; exit 1; }

ensure_apt_packages wget git python3-pip python3-venv libgl1 libglib2.0-0

git_clone_or_update https://github.com/AUTOMATIC1111/stable-diffusion-webui.git "$WEBUI_DIR"

cd "$WEBUI_DIR" || exit 1

# Install requirements WITHOUT letting them replace the ROCm PyTorch build.
if [ -f requirements.txt ]; then
    log "Installing Automatic1111 requirements (torch builds excluded)"
    rocm_ai_pip_filtered "$WEBUI_DIR/requirements.txt" || warn "Some requirements failed — continuing"
else
    warn "No requirements.txt found in $WEBUI_DIR"
fi

# --- webui-user.sh -----------------------------------------------------------
# Keep this minimal and honest. webui.sh sources it, and launch.sh supplies the
# real GPU environment, so anything set here risks conflicting with it.
if [ -f webui-user.sh ]; then
    cp webui-user.sh "webui-user.sh.backup.$(date +%Y%m%d%H%M%S)" 2>/dev/null || true
    log "Backed up the existing webui-user.sh"
fi

cat > webui-user.sh << 'WEBUI_USER_EOF'
#!/bin/bash
# ==============================================================================
# Generated by the ROCm WSL AI Toolkit.
#
# This file is intentionally minimal. The GPU environment (HSA_ENABLE_DXG_DETECTION,
# the MIOpen cache paths, HSA_OVERRIDE_GFX_VERSION handling) is applied by
# lib/launch.sh before this script runs, and the toolkit's tuned profile supplies
# the launch flags. Re-adding those settings here can conflict with the launcher
# and, in the case of HSA_OVERRIDE_GFX_VERSION, hide your GPU from PyTorch.
#
# Add your own extra flags below if you need them.
# ==============================================================================

export COMMANDLINE_ARGS="--listen --enable-insecure-extension-access --theme dark"

# Compute capability hints that are safe and useful on ROCm.
export PYTORCH_ROCM_ALLOW_UNALIGNED_ACCESS=1
WEBUI_USER_EOF

chmod +x webui-user.sh || warn "chmod on webui-user.sh failed"

# --- Extensions --------------------------------------------------------------
declare -a EXT_LIST=(
    "sd-webui-controlnet|https://github.com/Mikubill/sd-webui-controlnet.git"
    "openpose-editor|https://github.com/fkunn1326/openpose-editor.git"
    "stable-diffusion-webui-images-browser|https://github.com/AlUlkesh/stable-diffusion-webui-images-browser.git"
    "sd-webui-additional-networks|https://github.com/kohya-ss/sd-webui-additional-networks.git"
)

mkdir -p extensions
for entry in "${EXT_LIST[@]}"; do
    name="${entry%%|*}"
    repo="${entry##*|}"
    if [ ! -d "extensions/$name" ]; then
        log "Adding extension: $name"
        git clone --depth=1 "$repo" "extensions/$name" || { warn "Failed to clone $name"; continue; }
    else
        log "Updating extension: $name"
        git -C "extensions/$name" pull --rebase --autostash >/dev/null 2>&1 \
            || warn "Could not update $name — continuing"
    fi
    if [ -f "extensions/$name/requirements.txt" ]; then
        log "Installing requirements for $name"
        rocm_ai_pip_filtered "extensions/$name/requirements.txt" \
            || warn "Some requirements for $name failed — continuing"
    fi
done

# Remove the old hand-rolled ROCm launcher if a previous version created one; it
# contains the GPU-hiding override described at the top of this file.
if [ -f launch_webui_rocm.sh ]; then
    warn "Removing the obsolete launch_webui_rocm.sh (it set HSA_OVERRIDE_GFX_VERSION)"
    rm -f launch_webui_rocm.sh
fi

success "Automatic1111 installed."
cat <<EOF

  Location : $WEBUI_DIR
  Models   : $WEBUI_DIR/models/Stable-diffusion/
  Launch   : ./menu.sh  ->  Launch  ->  Automatic1111
             or: scripts/start/automatic1111.sh

EOF
